### PR TITLE
alpaca integration

### PR DESCRIPTION
**Pull request by smartchris84**
Alpaca is a new stock broker in US with Web API and WebSocket streaming with free commission. 

It would be a great value to add in backtrader to support the API.

Here are some links for the information.

https://alpaca.markets/
https://docs.alpaca.markets
https://github.com/alpacahq/alpaca-trade-api-python

### CODE REVIEW

**Comment by umitanuki** [comment]
Is there any process to get it merged in, or anything blocking so?

**Comment by backtrader** [comment]
Wouldn't it be better if you released it as a `pip` installable package?

```
pip install alpaca_backtrader
```

and the usage (just an example, names don't have to match what you have written)

```
import backtrader as bt
from alpaca_backtrader import AlpacaBroker

cerebro = bt.Cerebro()
cerebro.broker = AlpacaBroker(api_key='xxxxxxx')
...
```

**Comment by umitanuki** [comment]
Technically that works, but I would like to know why the other brokers are shipped together while this is not. If separating broker plugins works, should everything go that way?

**Comment by backtrader** [comment]
You probably don't realise that the question you posed crosses several lines, because there is no reason for me to justify why I do this or that.

But see, it is very easy, the *other brokers* were developed in conjunction with the rest of the framework by the author himself and undergo the same responsibilities and accountability.

If the broker developed by *alpaca* is integrated:

  - who is responsible for its maintenance?
  - who is accountable?

See for example this small thing, the file `backtrader/brokers/alpacabroker.py` contains the following copyright notice:

```
#
# Copyright (C) 2015, 2016, 2017 Daniel Rodriguez
#
```

You are granting me copyright of something which I didn't write. This makes me responsible and accountable. Although I am sure your code isn't problematic ... can you imagine what would happen if:

  - if you were infringing patents in your code?
  - if you had extracted code from other platforms and copied it verbatim?

I would be automatically, without having written a single comma, liable in front of a court for patent infringement or code plagiarism. Of course, this is probably far fetched, but real life is sometimes really harsh.

We could continue with something as simple as:

  - If the code has problems who is going to maintain the code?

I imagine you have founded a company because you are ready for the responsibility, accountability and the need to maintain the things you create, in exchange for money.

In my case, no company has been founded, there is no money flow and I keep the things within the management limits I am comfortable with.

**Comment by umitanuki** [comment]
Thanks for the explanation.  I totally respect where you stand, since I do have long experience working in the open source community and I know more than many people it is hard to keep the quality of the code and project itself as an open source project. I like how backtrader is today and I hear people like its cleanness and high quality, well documented comprehensive features. We can stay outside for the time being until more people express concern about it being outside. But as a company, we appreciate this age of open source where people are working in many areas at the level we can never reach to, and we do want to help and work with projects like backtrader. If you are open to more discussion, please reach out to me hitoshi@alpaca.markets. Thank you!

**Pull request closed without merging**
